// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web =  FirebaseOptions(
    apiKey: 'AIzaSyAtwrnINPDsbuAyWvEMdrqC2oBD6wT6VRw',
    appId: '1:811015802779:web:79612c5d0d60167adc1b3e',
    messagingSenderId: '811015802779',
    projectId: 'noteme-152e9',
    authDomain: 'noteme-152e9.firebaseapp.com',
    storageBucket: 'noteme-152e9.appspot.com',
  );

  static const FirebaseOptions android =   FirebaseOptions(
    apiKey: 'AIzaSyCfkkx7_g8tqmDdMYpcRfCsFKRZJ7nFitw',
    appId: '1:811015802779:android:0b447cdd4b242219dc1b3e',
    messagingSenderId: '811015802779',
    projectId: 'noteme-152e9',
    storageBucket: 'noteme-152e9.appspot.com',
  );

  static const FirebaseOptions ios =  FirebaseOptions(
    apiKey: 'AIzaSyAa6jCC9PVgPchmqkn7bf00MuN_qjW4EYo',
    appId: '1:811015802779:ios:fadb32b247e5330edc1b3e',
    messagingSenderId: '811015802779',
    projectId: 'noteme-152e9',
    storageBucket: 'noteme-152e9.appspot.com',
    iosClientId: '811015802779-s1q2mti4n8q5pgiujg45l0i648lind9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa6jCC9PVgPchmqkn7bf00MuN_qjW4EYo',
    appId: '1:811015802779:ios:fadb32b247e5330edc1b3e',
    messagingSenderId: '811015802779',
    projectId: 'noteme-152e9',
    storageBucket: 'noteme-152e9.appspot.com',
    iosClientId: '811015802779-s1q2mti4n8q5pgiujg45l0i648lind9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );
}
